# Build (source files and Storybook docs), lint and check format
name: Check format, lint and build
on:
  pull_request:
    branches:
      - main
jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Cache node modules
        uses: actions/cache@v2
        id: node-modules-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install modules
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Check formatting ✨
        run: yarn format:check

      - name: Lint ✨
        run: yarn lint

      - name: Build source files 🔧
        run: yarn build

      - name: Build docs 🔧
        run: yarn build:docs
